version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout 
      - run: apk --no-cache add git
      - run: go mod download
      - run: go build -o app
      - run: ./app